// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LAxsxO3RE8AB0EuH9w6iKTvRT5voZRQ',
    appId: '1:145943867850:web:d01ba9ba90032bcae2df33',
    messagingSenderId: '145943867850',
    projectId: 'shmr-to-do-app-lilykras',
    authDomain: 'shmr-to-do-app-lilykras.firebaseapp.com',
    storageBucket: 'shmr-to-do-app-lilykras.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNqwCr-w01G2-N6w1Lt_N7m_pG3fp4H2g',
    appId: '1:145943867850:android:caa7ac0d0855f61be2df33',
    messagingSenderId: '145943867850',
    projectId: 'shmr-to-do-app-lilykras',
    storageBucket: 'shmr-to-do-app-lilykras.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEh9ek8Zxa5iD9SG7ndJpX2JviPXS9e0',
    appId: '1:145943867850:ios:66be07bb4d1aa3e0e2df33',
    messagingSenderId: '145943867850',
    projectId: 'shmr-to-do-app-lilykras',
    storageBucket: 'shmr-to-do-app-lilykras.appspot.com',
    iosClientId:
        '145943867850-fk8mpjsf6l1648ctms6hflgf8ud67eka.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoList666',
  );
}
