name: Flutter CI

on: push
  

jobs:
  analyze:
    name: Analyzer and formatter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps: 
      - uses: actions/checkout@v2
      - uses: subosito/flutter-actions@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed .
  build:
    name: Build 
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
