# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on: push
  

jobs:
  analyze:
    name: Analyzer and formatter
    runs-on: ubunty-latest
    timeout-minutes: 10
    steps: 
      - uses: actions/checkout@v2
      - uses: subosito/flutter-actions@v2
        with:
          flutter-version: '3.10.4'
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed .
  
